title = "Scoring constants"

timeoutOffsetMillis = 1000

[availableMoves]
weight = 3.0
exp = 1.15

[location]
weight = 7.0
exp = 2.0

[double]
threshold = 0.4
minOffset = 0.2

[monteCarlo]
notificationFrequency = 100
doubleOffsetFactor = 1.6
doubleTimeDivider = 2.0

    [monteCarlo.light]
    explorationConstant = 3.0
    doubleThreshold = 5.0

    [monteCarlo.heavy]
    explorationConstant = 3.0
    doubleThreshold = 5.0


