title = "Scoring constants"

[availableMoves]
weight = 3.0
exp = 1.15

[location]
weight = 7.0
exp = 2.0

[double]
threshold = 0.4
minOffset = 0.2

[monteCarlo]
timoutOffsetMillis = 300
notificationFrequency = 100
explorationConstant = 2.0
mctsDoubleThreshold = 3.0
