title = "Scoring constants"

[availableMoves]
weight = 3.0
exp = 1.15

[location]
weight = 7.0
exp = 2.0

[tickets]
weight = 0.5

	[tickets.underground]
	weight = 0.30
	exp = 3.0

	[tickets.bus]
	weight = 0.2
	exp = 3.0

	[tickets.taxi]
	weight = 0.2
	exp = 3.0

[double]
threshold = 0.4
minOffset = 0.2

[secret]
threshold = 0.0
