title = "Scoring constants"

[availablemoves]
weight = 1.0
exp = 1.25

[location]
weight = 3.0
exp = 2.0

[tickets]
weight = 1.0

	[tickets.underground]
	weight = 0
	exp = 0

	[tickets.bus]
	weight = 0
	exp = 0

	[tickets.taxi]
	weight = 0
	exp = 0
